sudo: required
services:
  - docker

before_install:
  - docker build -t howarde8/dockerfrontendtest -f Dockerfile.dev .

script:
  - docker run -e CI=true howarde8/dockerfrontendtest npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  evn: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-093003787802"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"